server:
  port: 8000

spring:
  application:
    name: my-zuul-service

zuul:
  routes:
    first-service:
      path: /first/**
      url: http://127.0.0.1:8081
    second-service:
      path: /second/**
      url: http://127.0.0.1:8082