server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: my-apigateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: first-service
            uri:
              http://127.0.0.1:8081/
            predicates:
              - Path=/first/**
            # route to "http://127.0.0.1:8081/first/**"
            filters:
              - AddRequestHeader=first-service-req, first-service-req-header-new
              - AddResponseHeader=first-service-res, first-service-res-header-new
          - id: second-service
            uri:
              http://127.0.0.1:8082/
            predicates:
              - Path=/second/**
            # route to "http://127.0.0.1:8082/second/**"
            filters:
              - AddRequestHeader=second-service-req, second-service-req-header-new
              - AddResponseHeader=second-service-res, second-service-res-header-new